name: TESTS
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
          with:
            host: ${{ vars.GL_HOST }}
            trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
            access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
            id: '140'
            ref: 'master'
            variables: '{"URL_REPO":"${{ GITHUB.REPOSITORY }}", "BRANCH":"${{ GITHUB.REF_NAME }}", "GH_SHA":"${{ github.sha }}"}'
